### ISSUE TITLE
Rotation support

### ISSUE THREAD

**Issue by bonebox** [tellmarket/TAlertView#1]
Are there any plans to support landscape/rotation? If displayed while in landscape, it appears stretched, and rotating from portrait→landscape or vice versa doesn't resize properly.  

Also, it would be nice to have a property to disable the swipe-to-dismiss for those cases where the user must choose between a list of options.  That and/or a callback for when the view is swiped away so we can perform some action.

**Comment by washingtonmiranda** [comment]
Hi,
Thanks for the feedback!

We have plans to add support for screen rotation. Is not there because we don't need it, but I'll take it as a high priority and will be on the next release.

The flag to disable the user drag and the callback are good ideas, I think we'll add them on the next version.
